### ISSUE TITLE
Production ready? 

### ISSUE THREAD

**Issue by jdmarshall90** [paulw11/Seam3#1]
Is this library production ready?

**Comment by paulw11** [comment]
Seam3 is based on my fork of the original Seam library that I am using in a production app. My original fork addressed issues with `null` values and conflict resolution. Seam3 extends on this by addressing many code style issues to remove force-unwrapping and eliminate the use of globals.  

Seam3 also replaced the kind-of-implemented-but-non-functional reference code that was contained in the original Seam library. While I have tested this and I believe it works, I haven't used references in a production app yet.

The main feature that I still want to add is the mapping of binary Core Data attributes to `CKAssets`.  This won't change the library interfaces, so it shouldn't affect code that is already using the library when the new version is released. 

The short answer is, yes, it is production ready

**Comment by jdmarshall90** [comment]
By references, do you mean Core Data relationships, or something else?

**Comment by jdmarshall90** [comment]
And is it really as simple to integrate into an existing app as using the short snippets in the READ ME? If that's the case, this is awesome and I can't wait to use it.

**Comment by jdmarshall90** [comment]
One more question: are tvOS and macOS supported?

**Comment by paulw11** [comment]
The library maps one-to-many Core Data relationships to CloudKit references.  Many-to-one is supported as long as there is an inverse one-to-many.  Many-to-many relationships are not supported.

Aside from selecting an instance of SMStore as your backing store, you will probably want to implement the `NSNotification` handlers so that you can do something when a synchronisation takes place and you probably want to call `triggerSync` shortly after your app starts.  There is also some other checking you can do, such as verifying that the user is logged in to iCloud as the library doesn't do that (although it probably should).

I haven't tried it on tvOS and MacOS, as I am using it for an iOS app, but it should work; I will give it a try.

**Comment by cdf1982** [comment]
@paulw11 Thank you **very much** for resurrecting this project, I've always been tempted to use it, but I was scared by the lack of updates.
May I ask you for a clarification on this?

> Many-to-many relationships are not supported.

What does it mean? If my data model has two entities with many to many relationship, they can't sync via CloudKit?
Thanks in advance!
Cesare

**Comment by paulw11** [comment]
CloudKit `CKReference` objects do not support many-to-many relationships. If you try and use Seam3 with a core data model that contains a many-to-many relationship you will get an exception thrown. 

You can create an array attribute and store the identifiers of the related object (strings or whatever). This will mean that you need to perform a second query to retrieve the "related" objects rather than simply being able to follow the object reference as you can with a one-to-one or one-to-many atttribute.

**Comment by cdf1982** [comment]
Sadly I didn't realize that, sorry! And thank you so much for your explanation!
