### ISSUE TITLE
Migrate existing NSSQLiteStoreType to SMStore

### ISSUE THREAD

**Issue by horea4** [paulw11/Seam3#17]
Using migratePersistentStore to change the type of the store and move it to a new location results in a crash, but no error is caught in the try/catch block. I only get a generic "libc++abi.dylib: terminating with uncaught exception of type NSException" and no additional information about the crash. Has anyone successfully migrated an existing store to Seam?

**Comment by paulw11** [comment]
From my investigation it appears that `migratePersistentStore` creates a new instance of the target store, rather than using an existing instance.  Since `SMStore`s require additional initialisation (specifically, calling `verifyCloudKitConnectionAndUser`) there is a problem.  I am also seeing an exception related to the inability to contact the iCloud service; so there may be something else happening with the way that `migratePersistentStore` operates.

Unfortunately, this means that you will need to migrate your records to a `SMStore` in code.  I would suggest you set `syncAutomatically` to false while migrating your records and then perform a manual sync once the migration is complete.
