### ISSUE TITLE
http 500 error

### ISSUE THREAD

**Issue by Linasses** [paulw11/Seam3#22]
Hi Wilco,
I keep getting http 500 errors from the Seam3 demo app, have you encountered this issue too?
"Seam3_Example[16039:36358355] Unable to verify CloudKit Connection <CKError 0x608000243480: "Server Rejected Request" (2001); "Request failed with http status code 500">"
Any ideas?
Cheers
Linasses

**Comment by paulw11** [comment]
I haven't seen that.  Have you logged into iCloud and enabled iCloud drive on your device/simulator?

**Comment by Linasses** [comment]
I have. 
Thanks, I'll keep searching for the cause, I just didn't want to spend anymore time searching if it was an obvious fix. 

Cheers,

Linasses
Shawn Marston

**Comment by paulw11** [comment]
I searched for that error and I found a couple of hits that suggest either a temporary problem on Apple's end or a corrupted CloudKit container, so that isn't very helpful.   Try turning the cloudkit entitlement on/off in the sample app to reset your provisioning profile, or even try a different bundle id

**Comment by Linasses** [comment]
Thanks again Paul,
I had found those StackOverflows also, but seems to not be my issue. 
I'll try the 'turn it off and on again' trick. 

Cheers,

Linasses
Shawn Marston

**Comment by Linasses** [comment]
Hi Paul,

I have found the problem. 
Doh! Simple typo mismatch between the ProbBundleIdent and the options string. 

Cheers,

Shawn Marston
