### ISSUE TITLE
Implementing CKShare

### ISSUE THREAD

**Issue by blwinters** [paulw11/Seam3#73]
Thanks for the great library! I'd like to implement it in my project and also contribute code for adding CKShare functionality. Have you thought about what components would be needed to support this and how they might fit into the current sync process? 

In particular, how would a participant have access to a shared record in their main local store while sending changes to the owner's CloudKit database, instead of trying to sync it with their own private database? Do we need a property on every managed object to associate it with the correct CKDatabase? Also, how to manage subscriptions for changes on multiple shared databases?

I'm definitely going to write the code to add CKShare to my project, I just want to get a sense of whether the structure of Seam3 is fairly compatible or if I need to take a different approach entirely.

**Comment by paulw11** [comment]
While I can't see anything particularly difficult about adding a function to `SMStore` that returns a `CKShare` for a given `NSManagedObject`, I am not sure how the semantics of receiving a `CKShare` would work.  As much as possible, Seam3 hides CloudKit behind CoreData.  An incoming `CKShare` is not going to map to an `NSManagedObject` in the receiver's Seam3 environment since it is actually a reference to a shared `CKRecord` in the sharer's private database.

**Comment by blwinters** [comment]
That makes sense. I wasn't sure if there was a way to accommodate multiple databases within a single `SMStore`. I'll look into using a different sync architecture.
