### ISSUE TITLE
Uploading assets from documentDirectory

### ISSUE THREAD

**Issue by ghost** [paulw11/Seam3#91]
In my app I save images to documentDirectory and filePath to Core Data.
Then I get my filePath from CoreData and show it in UIImageView by contentsOfFile: filePath.path
Can i upload my image to Cloud from documentDirectory by filePath ? 
If it is impossible ,how can I make smh common to sync files ?

**Comment by paulw11** [comment]
Since Seam3 doesn't expose CloudKit directly there is no easy way to synchronise files into CloudKit using Seam3; You could write your own code to upload those files.

What I would suggest is that rather than saving images separately, you store them in Core Data as a binary attribute.  You can select the option to store binary data in external files in your Core Data model.  Seam3 will then transparently synchronise these to CloudKit as either data in the `CKRecord` or as a `CKAsset` (if you specified external storage)
